#!/usr/bin/python3

"""Print csv output from ini file.

Examples:
ini2csv -f $(ls -v out/*.ini)
ini2csv -f $(ls -v out/*.ini) -c Profit ObsNb WorkTime CompObsNb
ini2csv -f $(ls -v out/*.ini) -c Profit ObsNb WorkTime CompObsNb -t 120
"""

import initools

from argparse import ArgumentParser
import configparser

parser = ArgumentParser()
parser.add_argument("-f", "--files", dest="files", nargs='*', required=True,
                    help="input ini files", metavar="FILE")
parser.add_argument("-c", "--columns", dest="columns", nargs='*', required=False,
                    help="columns to extract")
parser.add_argument("-t", "--time", dest="time", required=False,
                    help="time", type=float)
args = parser.parse_args()

first = True
for f in args.files:
    ini = configparser.ConfigParser()
    ini.optionxform=str
    ini.read(f)

    # Find section
    if args.time == None:
        sec = ini.sections()[-1]
    else:
        sec = initools.get_section(ini, args.time);

    # Print column names the first time
    if first:
        if args.columns == None:
            print(*ini[sec], sep=",")
        else:
            print(*args.columns, sep=",")
        first = False

    # Print values
    if args.columns == None:
        l = [ini[sec][key] for key in ini[sec]]
    else:
        l = [ini[sec][key] for key in args.columns]
    print(*l, sep=",")

