#!/usr/bin/python3

"""Generate a plot file for Gnuplot from an ini file.

Example:
ini2plot "out/catussediscflex_7200_ins_400_71_1.ini" "Profit"
"""

import os
import sys
import configparser

inifile = sys.argv[1]
ini = configparser.ConfigParser()
ini.optionxform=str
ini.read(inifile)

key = sys.argv[2]

plotfile = os.path.splitext(inifile)[0] + '.plot'

f = open(plotfile, "w")
f.write("Time " + key + "\n")

k = 1
while "Solution" + str(k) in ini.sections():
    sec = "Solution" + str(k)
    f.write(ini[sec]["Time"] + " " + ini[sec][key] + "\n")
    k += 1
f.write(ini["Solution"]["Time"] + " " + ini[sec][key] + "\n")
f.close()

