cc_library(
        name = "info",
        hdrs = ["info.hpp"],
        srcs = [ ],
        visibility = ["//visibility:public"],
        deps = ["@json//:json"],
)

cc_library(
        name = "binary_heap",
        hdrs = ["binary_heap.hpp"],
        srcs = [ ],
        visibility = ["//visibility:public"],
)

