cc_library(
        name = "info",
        hdrs = ["info.hpp"],
        srcs = [ ],
        visibility = ["//visibility:public"],
        deps = ["@json//:json"],
)

cc_library(
        name = "indexed_collections",
        hdrs = [
                "indexed_set.hpp",
                "indexed_binary_heap.hpp",
        ],
        srcs = [ ],
        visibility = ["//visibility:public"],
)

