cc_library(
        name = "utils",
        hdrs = [
                "timer.hpp",
                "compose_stream.hpp",
                "logger.hpp",
                "parameters.hpp",
                "output.hpp",
                "utils.hpp",
        ],
        srcs = [
                "timer.cpp",
                "compose_stream.cpp",
                "logger.cpp",
                "parameters.cpp",
                "output.cpp",
        ],
        visibility = ["//visibility:public"],
        deps = ["@json//:json"],
)

