cc_library(
        name = "info",
        hdrs = ["info.hpp"],
        srcs = ["info.cpp"],
        visibility = ["//visibility:public"],
        deps = ["@json//:json"],
)

cc_library(
        name = "utils",
        hdrs = ["utils.hpp"],
        srcs = [ ],
        visibility = ["//visibility:public"],
)

