cc_library(
        name = "containers",
        hdrs = [
                "indexed_set.hpp",
                "indexed_map.hpp",
                "doubly_indexed_map.hpp",
                "indexed_binary_heap.hpp",
                "sorted_on_demand_array.hpp",
        ],
        srcs = [ ],
        visibility = ["//visibility:public"],
)

