cc_library(
        name = "graph",
        hdrs = [
                "abstract_graph.hpp",
                "adjacency_list_graph.hpp",
                "adjacency_matrix_graph.hpp",
                "segment_intersection_graph.hpp",
                "distance_two_bipartite_graph.hpp",
                "clique_graph.hpp",
        ],
        srcs = [ ],
        visibility = ["//visibility:public"],
)

